[env:esp32p4]
platform = https://github.com/platformio/platform-espressif32.git
framework = espidf
board = esp32-p4-ev-board
monitor_speed = 115200

build_flags = 
    -D CORE_DEBUG_LEVEL=5
    -D BOARD_HAS_PSRAM
    
# Automatically download camera and video components
board_build.cmake_extra_args = 
    -D SDKCONFIG_DEFAULTS="sdkconfig.defaults"
    